version: '{build}'
image: ubuntu
stack: jdk 8

cache:
  - /home/appveyor/.m2
install:
  - ps: .\build_scripts\UpdateBuildVersion.ps1
before_build:
  - mvn -v
build_script:
  - mvn clean package -DskipTests
test_script:
  - mvn install verify
test: off
#on_finish:
#  - sh: find "$APPVEYOR_BUILD_FOLDER" -type f -name 'TEST*.xml' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/junit/$APPVEYOR_JOB_ID"
artifacts:
  - path: "**/target/*.?ar"
    name: "SpriteCaster"
  - path: "**/target/*.exe"
    name: "SpriteCaster"
on_success:
  - ps: if ($env:APPVEYOR_REPO_BRANCH -eq "main") {.\build_scripts\discord-webhook.ps1 success $env:DISCORD_WEBHOOK_URL}
on_failure:
  - ps: if ($env:APPVEYOR_REPO_BRANCH -eq "main") {.\build_scripts\discord-webhook.ps1 failure $env:DISCORD_WEBHOOK_URL}
